"""describe change

Revision ID: 259841e5e905
Revises: fbf36cbabf3e
Create Date: 2026-04-21 15:35:10.170087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '259841e5e905'
down_revision = 'fbf36cbabf3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_site',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guest_uid', sa.Integer(), nullable=True),
    sa.Column('site_uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_column('site_uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    op.drop_table('guest_site')
    # ### end Alembic commands ###
