"""SitePhaseInverterSld

Revision ID: 7b3728716d6d
Revises: 20260224_sld
Create Date: 2026-02-24 08:52:37.285301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b3728716d6d'
down_revision = '20260224_sld'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_phase_inverter_sld',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inverter_uid', sa.Integer(), nullable=False),
    sa.Column('inv', sa.String(length=256), nullable=True),
    sa.Column('mppt', sa.String(length=256), nullable=True),
    sa.Column('string', sa.String(length=256), nullable=True),
    sa.Column('orientation', sa.String(length=64), nullable=True),
    sa.Column('tilt_angle', sa.Float(), nullable=True),
    sa.Column('module_wattage', sa.Float(), nullable=True),
    sa.Column('module_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inverter_uid'], ['site_phase_inverter.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_table('site_phase_sld')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_phase_sld',
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('phase_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('inv', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('mppt', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('string', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('orientation', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('tilt_angle', mysql.FLOAT(), nullable=True),
    sa.Column('module_wattage', mysql.FLOAT(), nullable=True),
    sa.Column('module_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['phase_uid'], ['site_phase.uid'], name=op.f('site_phase_sld_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('site_phase_inverter_sld')
    # ### end Alembic commands ###
