"""Remove guest_password from Site

Revision ID: afa3cc472741
Revises: 1ba5ad4718c2
Create Date: 2026-04-01 16:04:03.703458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afa3cc472741'
down_revision = '1ba5ad4718c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('guest_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_password', mysql.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
