"""Initial migration

Revision ID: e4effb042c8f
Revises: 20260202_rate
Create Date: 2026-02-02 16:58:30.032372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4effb042c8f'
down_revision = '20260202_rate'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('taipower_rate')

    with op.batch_alter_table('site_phase', schema=None) as batch_op:
        batch_op.drop_column('greenpower_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_phase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('greenpower_rate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taipower_rate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
