"""Add OptionAttachmentFile model

Revision ID: f3e5fa4d3e79
Revises: 6e03eb693ebb
Create Date: 2026-05-21 10:17:41.265481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3e5fa4d3e79'
down_revision = '6e03eb693ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_attachment_file',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_attachment_uid', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('user_name', sa.String(length=128), nullable=True),
    sa.Column('at_createdtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['option_attachment_uid'], ['option_attachment.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_table('option_attachment_anomaly_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_attachment_anomaly_file',
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('option_attachment_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('file_path', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('file_name', mysql.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['option_attachment_uid'], ['option_attachment.uid'], name=op.f('option_attachment_anomaly_file_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('option_attachment_file')
    # ### end Alembic commands ###
