"""Float

Revision ID: f41297f7e4c6
Revises: e4effb042c8f
Create Date: 2026-02-03 13:50:21.861967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f41297f7e4c6'
down_revision = 'e4effb042c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.alter_column('greenpower_rate',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('site_phase', schema=None) as batch_op:
        batch_op.alter_column('taipower_rate',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_phase', schema=None) as batch_op:
        batch_op.alter_column('taipower_rate',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.alter_column('greenpower_rate',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###
