"""Add Guest model

Revision ID: fbf36cbabf3e
Revises: afa3cc472741
Create Date: 2026-04-01 16:14:28.664721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf36cbabf3e'
down_revision = 'afa3cc472741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('site_uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest')
    # ### end Alembic commands ###
