"""Initial migration

Revision ID: fd38d71996a8
Revises: 
Create Date: 2026-05-25 14:33:27.069778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd38d71996a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('at_createdtime', sa.DateTime(), nullable=True),
    sa.Column('at_editedtime', sa.DateTime(), nullable=True),
    sa.Column('at_deletedtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('checklist_table',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('construction_table_group',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('design_table_group',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('guest',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('guest_site',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guest_uid', sa.Integer(), nullable=True),
    sa.Column('site_uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('site',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('build_date', sa.Date(), nullable=True),
    sa.Column('wait_cheack', sa.Boolean(), nullable=True),
    sa.Column('phase_number', sa.Integer(), nullable=True),
    sa.Column('user_uid', sa.Integer(), nullable=True),
    sa.Column('total_capacity', sa.Float(), nullable=True),
    sa.Column('latitude', sa.String(length=64), nullable=True),
    sa.Column('longitude', sa.String(length=64), nullable=True),
    sa.Column('installation_mode', sa.String(length=64), nullable=True),
    sa.Column('installation_env', sa.String(length=64), nullable=True),
    sa.Column('power_structure', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('line_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('checklist',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_uid', sa.Integer(), nullable=False),
    sa.Column('check_type', sa.Integer(), nullable=True),
    sa.Column('check_date', sa.Date(), nullable=True),
    sa.Column('user_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_uid'], ['site.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('checklist_table_option',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_uid'], ['checklist_table.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('construction_hazard_notice',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_uid', sa.Integer(), nullable=False),
    sa.Column('group_uid', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=4096), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('at_createdtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_uid'], ['construction_table_group.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_uid'], ['site.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('construction_table',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_uid'], ['construction_table_group.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('design_table',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_uid'], ['design_table_group.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('option_attachment',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_uid', sa.Integer(), nullable=False),
    sa.Column('option_uid', sa.Integer(), nullable=False),
    sa.Column('table_type', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['site_uid'], ['site.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('option_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_option_attachment_option_uid'), ['option_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_option_attachment_table_type'), ['table_type'], unique=False)

    op.create_table('site_phase',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('taipower_rate', sa.Float(), nullable=True),
    sa.Column('greenpower_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['site_uid'], ['site.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('checklist_table_option_data',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_uid', sa.Integer(), nullable=False),
    sa.Column('checklist_uid', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['checklist_uid'], ['checklist.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_uid'], ['checklist_table_option.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('construction_table_option',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_uid'], ['construction_table.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('design_checklist',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_uid', sa.Integer(), nullable=False),
    sa.Column('site_uid', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=4096), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('file_path_cad_1', sa.String(length=256), nullable=True),
    sa.Column('file_path_cad_2', sa.String(length=256), nullable=True),
    sa.Column('file_path_pdf', sa.String(length=256), nullable=True),
    sa.Column('at_createdtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_uid'], ['site.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_uid'], ['design_table.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('design_table_option',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_uid'], ['design_table.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('option_attachment_anomaly_breaker',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_attachment_uid', sa.Integer(), nullable=False),
    sa.Column('option_red', sa.Boolean(), nullable=True),
    sa.Column('option_black', sa.Boolean(), nullable=True),
    sa.Column('option_white', sa.Boolean(), nullable=True),
    sa.Column('option_blue', sa.Boolean(), nullable=True),
    sa.Column('option_yellow', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['option_attachment_uid'], ['option_attachment.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('option_attachment_anomaly_damaged',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_attachment_uid', sa.Integer(), nullable=False),
    sa.Column('file_path_front', sa.String(length=256), nullable=True),
    sa.Column('file_path_on', sa.String(length=256), nullable=True),
    sa.Column('file_path_below', sa.String(length=256), nullable=True),
    sa.Column('file_path_left', sa.String(length=256), nullable=True),
    sa.Column('file_path_right', sa.String(length=256), nullable=True),
    sa.Column('file_path_number', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['option_attachment_uid'], ['option_attachment.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('option_attachment_anomaly_image',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_attachment_uid', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['option_attachment_uid'], ['option_attachment.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('option_attachment_anomaly_optimizer',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_attachment_uid', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['option_attachment_uid'], ['option_attachment.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('option_attachment_anomaly_position',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_attachment_uid', sa.Integer(), nullable=False),
    sa.Column('inv', sa.Integer(), nullable=True),
    sa.Column('mppt', sa.Integer(), nullable=True),
    sa.Column('string', sa.Integer(), nullable=True),
    sa.Column('panel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['option_attachment_uid'], ['option_attachment.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('option_attachment_anomaly_reason',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_attachment_uid', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['option_attachment_uid'], ['option_attachment.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('option_attachment_anomaly_reason_setting',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checklist_option_uid', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_option_uid'], ['checklist_table_option.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('option_attachment_anomaly_state',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_attachment_uid', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['option_attachment_uid'], ['option_attachment.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('option_attachment_file',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_attachment_uid', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('user_name', sa.String(length=128), nullable=True),
    sa.Column('at_createdtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['option_attachment_uid'], ['option_attachment.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('option_attachment_for_checklist',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_attachment_uid', sa.Integer(), nullable=False),
    sa.Column('checklist_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_uid'], ['checklist.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_attachment_uid'], ['option_attachment.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('option_attachment_image',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_attachment_uid', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('user_name', sa.String(length=128), nullable=True),
    sa.Column('at_createdtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['option_attachment_uid'], ['option_attachment.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('option_attachment_note',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_attachment_uid', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['option_attachment_uid'], ['option_attachment.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('site_phase_inverter',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phase_uid', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=256), nullable=True),
    sa.Column('model', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['phase_uid'], ['site_phase.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('site_phase_module',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phase_uid', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=256), nullable=True),
    sa.Column('model', sa.String(length=256), nullable=True),
    sa.Column('wattage', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['phase_uid'], ['site_phase.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('construction_table_option_data',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_uid', sa.Integer(), nullable=False),
    sa.Column('site_uid', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['option_uid'], ['construction_table_option.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_uid'], ['site.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('design_table_option_data',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_uid', sa.Integer(), nullable=False),
    sa.Column('design_checklist_uid', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['design_checklist_uid'], ['design_checklist.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_uid'], ['design_table_option.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('site_phase_inverter_sld',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inverter_uid', sa.Integer(), nullable=False),
    sa.Column('inv', sa.String(length=256), nullable=True),
    sa.Column('mppt', sa.String(length=256), nullable=True),
    sa.Column('string', sa.String(length=256), nullable=True),
    sa.Column('orientation', sa.String(length=64), nullable=True),
    sa.Column('tilt_angle', sa.Float(), nullable=True),
    sa.Column('module_wattage', sa.Float(), nullable=True),
    sa.Column('module_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inverter_uid'], ['site_phase_inverter.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_phase_inverter_sld')
    op.drop_table('design_table_option_data')
    op.drop_table('construction_table_option_data')
    op.drop_table('site_phase_module')
    op.drop_table('site_phase_inverter')
    op.drop_table('option_attachment_note')
    op.drop_table('option_attachment_image')
    op.drop_table('option_attachment_for_checklist')
    op.drop_table('option_attachment_file')
    op.drop_table('option_attachment_anomaly_state')
    op.drop_table('option_attachment_anomaly_reason_setting')
    op.drop_table('option_attachment_anomaly_reason')
    op.drop_table('option_attachment_anomaly_position')
    op.drop_table('option_attachment_anomaly_optimizer')
    op.drop_table('option_attachment_anomaly_image')
    op.drop_table('option_attachment_anomaly_damaged')
    op.drop_table('option_attachment_anomaly_breaker')
    op.drop_table('design_table_option')
    op.drop_table('design_checklist')
    op.drop_table('construction_table_option')
    op.drop_table('checklist_table_option_data')
    op.drop_table('site_phase')
    with op.batch_alter_table('option_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_option_attachment_table_type'))
        batch_op.drop_index(batch_op.f('ix_option_attachment_option_uid'))

    op.drop_table('option_attachment')
    op.drop_table('design_table')
    op.drop_table('construction_table')
    op.drop_table('construction_hazard_notice')
    op.drop_table('checklist_table_option')
    op.drop_table('checklist')
    op.drop_table('user')
    op.drop_table('site')
    op.drop_table('guest_site')
    op.drop_table('guest')
    op.drop_table('design_table_group')
    op.drop_table('construction_table_group')
    op.drop_table('checklist_table')
    op.drop_table('auth')
    # ### end Alembic commands ###
